let active='',deferredInstallPrompt=null;
const chunks=['0.txt','1.txt','2a.txt','2b.txt','3.txt','4.txt','5.txt','6.txt'];
async function loadSprite(){try{const p=await Promise.all(chunks.map(x=>fetch('../v11/imgv2/'+x).then(r=>r.text())));document.documentElement.style.setProperty('--sprite-image',`url("data:image/jpeg;base64,${p.join('')}")`)}catch(e){console.warn('Imagem não carregou',e)}}
function startWorkout(k){active=k;home.style.display='none';summary.style.display='none';session.style.display='block';title.textContent=`Treino ${k} • ${DATA[k].title}`;renderWorkout();scrollTo(0,0)}
function renderWorkout(){const a=DATA[active].items;counter.textContent=`0/${a.length}`;bar.style.width='0%';content.innerHTML=a.map((x,i)=>`<article class="card"><div class="photo" style="background-position:${x[7]*100/3}% ${x[8]*100/3}%"></div><div class="head"><span class="num">${i+1}</span><div><h2>${x[0]}</h2><small>${x[1]}</small><div class="badge">Adaptação • fácil de encontrar</div></div></div><div class="meta"><div><b>SÉRIES</b><span>${x[2]}</span></div><div><b>REPETIÇÕES</b><span>${x[3]}</span></div><div><b>DESCANSO</b><span>60–90 s</span></div></div><div class="tip"><b>Como executar</b><br>${x[4]}</div><div class="alt"><b>Alternativa se estiver lotado</b><br>${x[5]}<br><small>${x[6]}</small></div><div class="exerciseDone"><input type="checkbox" id="d${i}" onchange="updateProgress()"><label for="d${i}"><b>Marcar como concluído</b></label></div></article>`).join('')}
function updateProgress(){const t=DATA[active].items.length,d=[...document.querySelectorAll('.exerciseDone input')].filter(x=>x.checked).length;counter.textContent=`${d}/${t}`;bar.style.width=`${d/t*100}%`}
function clearChecks(){document.querySelectorAll('.exerciseDone input').forEach(x=>x.checked=false);updateProgress()}
function finishWorkout(){const t=DATA[active].items.length,d=[...document.querySelectorAll('.exerciseDone input')].filter(x=>x.checked).length;session.style.display='none';summary.style.display='block';summaryText.textContent=`Treino ${active} • ${d} de ${t} exercícios concluídos.`;scrollTo(0,0)}
function goHome(){session.style.display='none';summary.style.display='none';home.style.display='block';active='';scrollTo(0,0)}
function standalone(){return matchMedia('(display-mode:standalone)').matches||navigator.standalone===true}
function help(){const u=navigator.userAgent;if(/iPhone|iPad|iPod/i.test(u))return 'No iPhone/iPad: Compartilhar → Adicionar à Tela de Início.';if(/SamsungBrowser/i.test(u))return 'No Samsung Internet: menu ☰ → Adicionar página a → Tela inicial.';return 'No Android/Chrome: menu ⋮ → Instalar app ou Adicionar à tela inicial.'}
function installUI(){if(standalone()){installBtn.hidden=true;standaloneNote.classList.add('show')}else{installBtn.hidden=false;standaloneNote.classList.remove('show')}}
addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;installUI()});addEventListener('appinstalled',()=>{deferredInstallPrompt=null;installUI()});
installBtn.onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();try{await deferredInstallPrompt.userChoice}catch(e){}deferredInstallPrompt=null;installUI()}else{installHelp.textContent=help();installHelp.classList.toggle('show')}};
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
loadSprite();installUI();const t=new URLSearchParams(location.search).get('treino');if(DATA[t])addEventListener('load',()=>startWorkout(t));